//! The Reborn extension package for the canvas tool.
//!
//! A second host-bundled MCP extension alongside `ic-browser`, registered the
//! exact same way (CP-4 loopback exemption; catalogue scanned once at gateway
//! boot; discovery at activation; re-activate every launch). The only differences
//! from the browser manifest are the id, the single tool, and that the server it
//! points at runs **in the widget process**, not a child.
//!
//! The same three timing rules apply — see `ic_widget`'s canvas supervision for
//! where they are enforced. Reborn discards the capability declared below and
//! rebuilds it from the live `tools/list`, so this is only a template; the real
//! `canvas_render` schema comes from [`crate::protocol`].

use crate::server::MCP_PATH;

/// The extension id, the directory name, and the capability-id prefix
/// (`ic-canvas.canvas_render`).
pub const EXTENSION_ID: &str = "ic-canvas";

/// The manifest for the in-process canvas server listening on `port`.
///
/// `url` pins `127.0.0.1` (a literal loopback IP), which is what CP-4 requires —
/// `localhost` would be refused, because a DNS name could be rebound.
pub fn manifest_toml(port: u16) -> String {
    let url = format!("http://127.0.0.1:{port}{MCP_PATH}");
    format!(
        r#"# Generated by ic_widget on launch — do not edit by hand.
#
# The canvas MCP server runs INSIDE the widget process (unlike the browser
# sidecar, which is a child process), because rendering must reach a Tauri window.
# The port is baked into `url`; Reborn pins its egress allowlist to this exact
# host:port, so a change means rewriting this file and restarting the gateway.
schema_version = "reborn.extension_manifest.v2"
id = "{EXTENSION_ID}"
name = "Canvas"
version = "0.1.0"
description = "Display HTML or SVG on the desktop canvas window — charts, tables, diagrams, documents."
trust = "third_party"

[runtime]
kind = "mcp"
transport = "http"
url = "{url}"

# A TEMPLATE. Reborn replaces this with the capability it discovers from the
# server's `tools/list`, keeping only the fields below. canvas_render is a pure
# display action, so it declares no external-write effect.
[[capabilities]]
id = "{EXTENSION_ID}.canvas_render"
description = "Display HTML or SVG on the desktop canvas window."
effects = ["dispatch_capability", "network"]
default_permission = "allow"
visibility = "model"
input_schema_ref = "schemas/{EXTENSION_ID}/canvas_render.input.v1.json"
output_schema_ref = "schemas/{EXTENSION_ID}/canvas_render.output.v1.json"
required_host_ports = ["host.runtime.http_egress"]
"#
    )
}

/// The template capability's input schema, for the one file the materialize step
/// wants on disk. The discovered capability carries its schema inline.
pub fn template_input_schema() -> String {
    serde_json::to_string_pretty(&crate::protocol::canvas_render_descriptor()["inputSchema"])
        .unwrap_or_else(|_| "{}".to_string())
}

/// The template capability's output schema. Permissive: the real output is an MCP
/// `content` block that Reborn passes through.
pub fn template_output_schema() -> String {
    serde_json::to_string_pretty(&serde_json::json!({
        "type": "object",
        "additionalProperties": true,
    }))
    .unwrap_or_else(|_| "{}".to_string())
}

/// Write the extension package into `extensions_root`, creating
/// `<extensions_root>/ic-canvas/`. Idempotent; overwrites, because a stale port is
/// worse than no extension.
pub fn install_package(extensions_root: &std::path::Path, port: u16) -> std::io::Result<()> {
    let package_root = extensions_root.join(EXTENSION_ID);
    let schema_dir = package_root.join("schemas").join(EXTENSION_ID);
    std::fs::create_dir_all(&schema_dir)?;

    std::fs::write(package_root.join("manifest.toml"), manifest_toml(port))?;
    std::fs::write(
        schema_dir.join("canvas_render.input.v1.json"),
        template_input_schema(),
    )?;
    std::fs::write(
        schema_dir.join("canvas_render.output.v1.json"),
        template_output_schema(),
    )?;
    tracing::info!(root = %package_root.display(), port, "installed the canvas extension manifest");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_manifest_pins_a_loopback_ip_and_declares_the_hosted_http_mcp_shape() {
        let manifest = manifest_toml(8945);
        assert!(
            manifest.contains(r#"url = "http://127.0.0.1:8945/mcp""#),
            "{manifest}"
        );
        assert!(!manifest.contains("localhost"));
        // hosted_http_mcp_url requires exactly this shape: http transport, a url,
        // no command, no args.
        assert!(manifest.contains(r#"kind = "mcp""#));
        assert!(manifest.contains(r#"transport = "http""#));
        assert!(!manifest.contains("command"));
        assert!(!manifest.contains("args"));
    }

    #[test]
    fn the_template_capability_is_prefixed_and_declares_no_write() {
        let manifest = manifest_toml(1);
        assert!(manifest.contains(&format!("id = \"{EXTENSION_ID}.canvas_render\"")));
        // canvas_render only shows content; classifying it as a write would gate
        // every chart behind approval for no reason.
        assert!(!manifest.contains("external_write"));
    }

    #[test]
    fn install_writes_a_manifest_and_its_template_schemas() {
        let temp = tempfile::tempdir().unwrap();
        install_package(temp.path(), 5544).unwrap();
        let root = temp.path().join(EXTENSION_ID);
        assert!(root.join("manifest.toml").is_file());
        assert!(
            root.join("schemas")
                .join(EXTENSION_ID)
                .join("canvas_render.input.v1.json")
                .is_file()
        );
        let manifest = std::fs::read_to_string(root.join("manifest.toml")).unwrap();
        assert!(manifest.contains("127.0.0.1:5544"));
    }
}
