//! The Reborn extension package for this sidecar.
//!
//! Reborn learns about the browser tools by scanning
//! `<reborn-home>/local-dev/system/extensions/<id>/manifest.toml` at boot. The
//! manifest lives here rather than in `ic_widget` because it has to agree with
//! [`crate::protocol`] — the extension id, the capability-id prefix, and the tool
//! names are one contract, and splitting them across crates is how they drift.
//!
//! ## The three timing rules this package obeys
//!
//! These are properties of the runtime, learned the hard way; violating any one
//! of them yields an extension that looks installed and has no tools:
//!
//! 1. **The catalogue is scanned once, at `serve` boot.** The manifest must be on
//!    disk *before* the gateway starts. A file dropped in later is invisible
//!    until the next restart.
//! 2. **Tool discovery happens at *activation*, not at boot.** Reborn calls our
//!    `tools/list` when the extension is activated, so the sidecar must be
//!    listening at that moment — and activation must be driven against the
//!    *running* gateway.
//! 3. **A restart does not re-discover.** `restore_extension_lifecycle_state`
//!    republishes the *bundled manifest*, which carries only the capability
//!    template below — not the six real tools. So the widget re-activates on every
//!    launch. A transient discovery failure *silently* falls back to the template,
//!    which is why the widget verifies the capability count instead of trusting
//!    that activation "succeeded".
//!
//! ## Why there is only one capability here
//!
//! Reborn **discards** these declarations and rebuilds every capability from the
//! live `tools/list` (`hosted_mcp_discovery::package_with_discovered_hosted_mcp_tools`).
//! What survives from this file is only the *template*: `required_host_ports`,
//! `runtime_credentials`, `resource_profile`, and whether the provider declares
//! any write effect. So one representative capability is all that belongs here —
//! the real six come from [`crate::protocol::ALL_TOOLS`].

use crate::server::MCP_PATH;

/// The extension id. Also the directory name under `/system/extensions/`, and the
/// prefix of every capability id (`ic-browser.browser_navigate`, …).
pub const EXTENSION_ID: &str = "ic-browser";

/// The manifest for a sidecar listening on `port`.
///
/// `url` is pinned to `127.0.0.1` — not `localhost`. CP-4 only exempts a literal
/// loopback **IP**, precisely because a DNS name could be rebound; a `localhost`
/// URL here would be refused by the very patch that makes this work.
pub fn manifest_toml(port: u16) -> String {
    let url = format!("http://127.0.0.1:{port}{MCP_PATH}");
    format!(
        r#"# Generated by ic_widget on launch — do not edit by hand.
#
# The port is baked into `url` because Reborn pins its egress allowlist to this
# exact host:port. If the sidecar's port changes, this file must be rewritten and
# the gateway restarted (the extension catalogue is only scanned at boot).
schema_version = "reborn.extension_manifest.v2"
id = "{EXTENSION_ID}"
name = "Browser"
version = "0.1.0"
description = "Drive a dedicated Chrome/Edge instance: navigate, read pages, find elements, fill inputs, click, and screenshot."
trust = "third_party"

[runtime]
kind = "mcp"
transport = "http"
url = "{url}"

# A TEMPLATE, not the tool list. Reborn replaces this with the six capabilities it
# discovers from the sidecar's `tools/list`, keeping only the fields below.
# `external_write` is declared so that any tool which arrives *unannotated* is
# treated conservatively as a write rather than a read.
[[capabilities]]
id = "{EXTENSION_ID}.browser_navigate"
description = "Load a URL in the browser and wait for it to settle."
effects = ["dispatch_capability", "network", "external_write"]
default_permission = "ask"
visibility = "model"
input_schema_ref = "schemas/{EXTENSION_ID}/browser_navigate.input.v1.json"
output_schema_ref = "schemas/{EXTENSION_ID}/browser_navigate.output.v1.json"
required_host_ports = ["host.runtime.http_egress"]
"#
    )
}

/// The template capability's input schema.
///
/// Only the *template* needs a file on disk; the discovered capabilities carry
/// their schemas inline, straight from our `tools/list`.
pub fn template_input_schema() -> String {
    let schema = crate::protocol::Tool::BrowserNavigate.input_schema();
    serde_json::to_string_pretty(&schema).unwrap_or_else(|_| "{}".to_string())
}

/// The template capability's output schema. Deliberately permissive: the real
/// outputs are MCP `content` blocks, which Reborn passes through as-is.
pub fn template_output_schema() -> String {
    serde_json::to_string_pretty(&serde_json::json!({
        "type": "object",
        "additionalProperties": true,
    }))
    .unwrap_or_else(|_| "{}".to_string())
}

/// Write the extension package into `extensions_root` (i.e.
/// `<reborn-home>/local-dev/system/extensions`), creating
/// `<extensions_root>/ic-browser/`.
///
/// Idempotent: it overwrites, because the port changes the manifest and a stale
/// `url` is worse than no extension at all.
pub fn install_package(extensions_root: &std::path::Path, port: u16) -> std::io::Result<()> {
    let package_root = extensions_root.join(EXTENSION_ID);
    let schema_dir = package_root.join("schemas").join(EXTENSION_ID);
    std::fs::create_dir_all(&schema_dir)?;

    std::fs::write(package_root.join("manifest.toml"), manifest_toml(port))?;
    std::fs::write(
        schema_dir.join("browser_navigate.input.v1.json"),
        template_input_schema(),
    )?;
    std::fs::write(
        schema_dir.join("browser_navigate.output.v1.json"),
        template_output_schema(),
    )?;
    tracing::info!(root = %package_root.display(), port, "installed the browser extension manifest");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_manifest_pins_a_loopback_ip_not_a_hostname() {
        let manifest = manifest_toml(8931);
        assert!(
            manifest.contains(r#"url = "http://127.0.0.1:8931/mcp""#),
            "{manifest}"
        );
        // `localhost` would be refused by CP-4, which requires an IP literal.
        assert!(!manifest.contains("localhost"));
    }

    #[test]
    fn the_manifest_declares_the_hosted_http_mcp_runtime_shape() {
        // `hosted_http_mcp_url` requires exactly this: transport "http", a url,
        // no `command`, and no `args`. Anything else and the package silently
        // fails to qualify as a hosted-MCP provider and never gets discovered.
        let manifest = manifest_toml(1234);
        assert!(manifest.contains(r#"kind = "mcp""#));
        assert!(manifest.contains(r#"transport = "http""#));
        assert!(!manifest.contains("command"));
        assert!(!manifest.contains("args"));
    }

    #[test]
    fn the_template_declares_a_write_effect_so_unannotated_tools_stay_conservative() {
        // `discovered_tool_requires_external_write` falls back to "does the
        // provider declare any write?" for tools with no annotations. Dropping
        // `external_write` here would quietly downgrade such a tool to a read.
        assert!(manifest_toml(1).contains("external_write"));
    }

    #[test]
    fn the_template_capability_id_is_prefixed_with_the_extension_id() {
        // Reborn builds capability ids as `<extension>.<tool>`; a template whose
        // id lacks the prefix fails manifest validation.
        assert!(manifest_toml(1).contains(&format!("id = \"{EXTENSION_ID}.browser_navigate\"")));
    }

    #[test]
    fn install_package_writes_a_manifest_and_its_template_schemas() {
        let temp = tempfile::tempdir().expect("tempdir");
        install_package(temp.path(), 4321).expect("install");

        let package_root = temp.path().join(EXTENSION_ID);
        let manifest = std::fs::read_to_string(package_root.join("manifest.toml")).expect("read");
        assert!(manifest.contains("127.0.0.1:4321"));

        // The catalogue keys the package by directory name, so it must equal the
        // manifest id or the scan drops it.
        assert!(package_root.is_dir());
        assert!(
            package_root
                .join("schemas")
                .join(EXTENSION_ID)
                .join("browser_navigate.input.v1.json")
                .is_file()
        );
    }

    #[test]
    fn reinstalling_with_a_new_port_replaces_the_stale_url() {
        let temp = tempfile::tempdir().expect("tempdir");
        install_package(temp.path(), 1111).expect("first install");
        install_package(temp.path(), 2222).expect("second install");

        let manifest =
            std::fs::read_to_string(temp.path().join(EXTENSION_ID).join("manifest.toml"))
                .expect("read");
        assert!(manifest.contains("127.0.0.1:2222"));
        assert!(!manifest.contains("1111"), "a stale port must not survive");
    }
}
